#!/bin/bash
# Copyright 2022 VMware, Inc.
# SPDX-License-Identifier: Apache-2.0

# THIS TEST HAS MUCH LOWER LIMITS IN ORDER TO PASS. SEE CPP FOR ACTUAL LIMITS.
export TORONI_AGENT_RINGBUF_SIZE_KB=64
export TORONI_AGENT_MESSAGE_SIZE_BYTES=10
export TORONI_AGENT_BACKPRESSURE_SLEEP_MS=200
export TORONI_AGENT_MESSAGES_PER_WRITER=20000
export TORONI_AGENT_TEST_FLAVOR=FIRST_LAST_DURATION
export TORONI_AGENT_ITERATIONS=1

(source ./setup-agent.sh && cd $SYSTEM_TESTS_ROOT/burst && ./bench-cell.sh 5 5 result)